name: Build, Test, and Audit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run Jest tests
        run: npm test

      - name: Run npm audit
        run: npm audit
